apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app
  labels:
    app: devopsApp 
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: devopsApp
  template:
    metadata:
      labels:
        app: devopsApp
    spec:
      containers:
      - name: tomcat
        image: dtr.nagarro.com:443/i-abhishekgoyal-master:14
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: devopsApp
  ports:
  - name: port8080
    protocol: TCP
    nodePort: {{ .Values.nodePort }}
    port: 8080
    targetPort: 8080

